---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: /consul
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /etcd
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /eureka
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /nacos
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /polaris
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /redis
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /servicecomb
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /zookeeper
    schedule:
      interval: weekly

